# Generated by Django 5.0.14 on 2026-01-11 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wgadmin', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrafficSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('public_key', models.CharField(db_index=True, max_length=44)),
                ('client_name', models.CharField(blank=True, default='', max_length=255)),
                ('rx_bytes', models.BigIntegerField(help_text='Полученные байты (cumulative)')),
                ('tx_bytes', models.BigIntegerField(help_text='Отправленные байты (cumulative)')),
                ('total_bytes', models.BigIntegerField(help_text='rx_bytes + tx_bytes')),
            ],
            options={
                'verbose_name': 'Traffic Snapshot',
                'verbose_name_plural': 'Traffic Snapshots',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['public_key', '-timestamp'], name='wgadmin_tra_public__1ac8c8_idx'), models.Index(fields=['-timestamp'], name='wgadmin_tra_timesta_36b6d1_idx')],
            },
        ),
    ]
